"""
Django settings for restaurant_booking project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-&ov3omnys)-lzmv9l@y-@k9+p=15vw=9*jy+6$!6iau&x&&pp@'
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-&ov3omnys)-lzmv9l@y-@k9+p=15vw=9*jy+6$!6iau&x&&pp@')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = ['betterinthyme-2fdd2e78de0c.herokuapp.com']
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    os.environ.get('HEROKU_HOSTNAME'),  
    '8000-tammygirl20-betterinthy-nkg6dhlbs5w.ws.codeinstitute-ide.net', 
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'restaurant_booking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'restaurant_booking.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#   'default': dj_database_url.parse('postgresql://bit_owner:GWLQ3h0gIOcj@ep-wispy-resonance-a2dn6ucw.eu-central-1.aws.neon.tech/bit?sslmode=require')
# }

DATABASES = {
    'default': dj_database_url.parse(os.environ.get('DATABASE_URL', 'sqlite:///db.sqlite3'))

}


# DATABASES = {
 #   'default': {
 #       'default': dj_database_url.config(default=os.getenv('DATABASE_URL')),
  #      'ENGINE': 'django.db.backends.postgresql',
  #      'NAME': 'bit',  # Replace this with your database name
 #       'USER': 'bit_owner',  # Replace this with your database username
 #       'PASSWORD': 'GWLQ3h0gIOcj',  # Replace this with your database password
 #       'HOST': 'ep-wispy-resonance-a2dn6ucw.eu-central-1.aws.neon.tech',  # Replace this with your database host
#        'PORT': '5432',  # Default PostgreSQL port
 #       'OPTIONS': {
  #          'sslmode': 'require',
 #       },
 #   }
#}



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'bookings', 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

